/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package plantcaremanager.UI;

import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.time.format.FormatStyle;
import plantcaremanager.*;
import plantcaremanager.PlantCareManager;


/**
 *
 * @author kelvi
 */
public class HomePage extends javax.swing.JFrame {

    private PlantCareManager manager = new PlantCareManager();

    public HomePage() {
        initComponents();
        initLists();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabScreen = new javax.swing.JTabbedPane();
        pnlHome = new javax.swing.JPanel();
        lblTitleHome = new javax.swing.JLabel();
        lblSelectHome = new javax.swing.JLabel();
        btgPlantsHome = new javax.swing.JButton();
        btgNotesHome = new javax.swing.JButton();
        btgTasksHome = new javax.swing.JButton();
        lblTasksDueHome = new javax.swing.JLabel();
        scrScrollListHome = new javax.swing.JScrollPane();
        lstTasksDue = new javax.swing.JList<>();
        lblCurrentDateHome = new javax.swing.JLabel();
        lblHelp = new javax.swing.JButton();
        pnlPlantManager = new javax.swing.JPanel();
        btnSavePlant = new javax.swing.JButton();
        scrNotesPlant = new javax.swing.JScrollPane();
        txaNotesPlant = new javax.swing.JTextArea();
        txtAddPlant = new javax.swing.JTextField();
        btnAddPlant = new javax.swing.JButton();
        lblSortPlant = new javax.swing.JLabel();
        cmbSortPlant = new javax.swing.JComboBox<>();
        btnCancelPlant = new javax.swing.JButton();
        lblLabelPlant = new javax.swing.JLabel();
        btnAddLabelPlant = new javax.swing.JButton();
        btnDeletePlant = new javax.swing.JButton();
        btnEditPlant = new javax.swing.JButton();
        txtNamePlant = new javax.swing.JTextField();
        lblHeadingPlant = new javax.swing.JLabel();
        scrListPlant = new javax.swing.JScrollPane();
        lstListPlant = new javax.swing.JList<>();
        txtAssignedLabelPlant = new javax.swing.JTextField();
        cmbLabelPlant = new javax.swing.JComboBox<>();
        txtAddLabelPlant = new javax.swing.JTextField();
        btnAddLabelTXTPlant = new javax.swing.JButton();
        lblChangeLabelPlant = new javax.swing.JLabel();
        lblDefaultLabelPlant = new javax.swing.JLabel();
        lblAddOwnLabelPlant = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        pnlEncryptedNotesManager = new javax.swing.JPanel();
        scrListNote = new javax.swing.JScrollPane();
        lstListNote = new javax.swing.JList<>();
        lblHeadingNote = new javax.swing.JLabel();
        btnSaveNote = new javax.swing.JButton();
        btnEditNote = new javax.swing.JButton();
        btnDeleteNote = new javax.swing.JButton();
        scrNote = new javax.swing.JScrollPane();
        txaNote = new javax.swing.JTextArea();
        lblSortNote = new javax.swing.JLabel();
        cmbSortNote = new javax.swing.JComboBox<>();
        btnCancelNote = new javax.swing.JButton();
        txtAddNote = new javax.swing.JTextField();
        btnAddNote = new javax.swing.JButton();
        txtNameNote = new javax.swing.JTextField();
        btnChangePasswordNote = new javax.swing.JButton();
        txtPasswordNote = new javax.swing.JTextField();
        lblPassword = new javax.swing.JLabel();
        btnLockNote = new javax.swing.JButton();
        btnUnlockNote = new javax.swing.JButton();
        pnlTaskManager = new javax.swing.JPanel();
        btnDeleteTask = new javax.swing.JButton();
        btnSaveTask = new javax.swing.JButton();
        btnEditTask = new javax.swing.JButton();
        btnCancelTask = new javax.swing.JButton();
        scrNoteTask = new javax.swing.JScrollPane();
        txaNotesTask = new javax.swing.JTextArea();
        tglCompleteTask = new javax.swing.JToggleButton();
        lblHeadingTask = new javax.swing.JLabel();
        scrListTask = new javax.swing.JScrollPane();
        lstListTask = new javax.swing.JList<>();
        cmbFilterTask = new javax.swing.JComboBox<>();
        lblFilterTask = new javax.swing.JLabel();
        lblSortTask = new javax.swing.JLabel();
        cmbSortTask = new javax.swing.JComboBox<>();
        lblAssignedLabelTask = new javax.swing.JLabel();
        txtAddTask = new javax.swing.JTextField();
        btnAddTask = new javax.swing.JButton();
        dpDueDateTask = new com.github.lgooddatepicker.components.DatePicker();
        lblDueDateTask = new javax.swing.JLabel();
        btnSaveDateTask = new javax.swing.JButton();
        txtNameTask = new javax.swing.JTextField();
        lblChangeLabelTask = new javax.swing.JLabel();
        lblDefaultLabelTask = new javax.swing.JLabel();
        cmbLabelTask = new javax.swing.JComboBox<>();
        btnAddLabelTask = new javax.swing.JButton();
        txtAddLabelTask = new javax.swing.JTextField();
        btnAddLabelTXTTask = new javax.swing.JButton();
        lblAddLabelTask = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        txtAssignedLabelTask = new javax.swing.JTextField();
        mnuMenu = new javax.swing.JMenuBar();
        mnuQuickActions = new javax.swing.JMenu();
        mniDownloadPlantList = new javax.swing.JMenuItem();
        mniDownloadTaskList = new javax.swing.JMenuItem();
        mniSyncTasks = new javax.swing.JMenuItem();
        mniSaveData = new javax.swing.JMenuItem();
        mnuHelp = new javax.swing.JMenu();
        mniContactUs = new javax.swing.JMenuItem();
        mniFAQ = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblTitleHome.setText("Welcome to the Plant Care Manager");
        lblTitleHome.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N

        lblSelectHome.setText("Please select your destination: ");
        lblSelectHome.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        btgPlantsHome.setText("Manage Your Plants");
        btgPlantsHome.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        btgPlantsHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btgPlantsHomeActionPerformed(evt);
            }
        });

        btgNotesHome.setText("Manage Your Encrypted Notes");
        btgNotesHome.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        btgNotesHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btgNotesHomeActionPerformed(evt);
            }
        });

        btgTasksHome.setText("Manage Your Tasks");
        btgTasksHome.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        btgTasksHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btgTasksHomeActionPerformed(evt);
            }
        });

        lblTasksDueHome.setText("Tasks Due This Week");
        lblTasksDueHome.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        lstTasksDue.setEnabled(false);
        lstTasksDue.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        lstTasksDue.setSelectedIndex(0);
        scrScrollListHome.setViewportView(lstTasksDue);

        lblCurrentDateHome.setText("Date: " + LocalDate.now().format(DateTimeFormatter.ofLocalizedDate(FormatStyle.LONG)));

        lblHelp.setText("Help");
        lblHelp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lblHelpActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlHomeLayout = new javax.swing.GroupLayout(pnlHome);
        pnlHome.setLayout(pnlHomeLayout);
        pnlHomeLayout.setHorizontalGroup(
            pnlHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHomeLayout.createSequentialGroup()
                .addGroup(pnlHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlHomeLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(btgPlantsHome)
                        .addGap(18, 18, 18)
                        .addComponent(btgNotesHome)
                        .addGap(18, 18, 18)
                        .addComponent(btgTasksHome))
                    .addGroup(pnlHomeLayout.createSequentialGroup()
                        .addGap(187, 187, 187)
                        .addComponent(lblTitleHome)))
                .addContainerGap(39, Short.MAX_VALUE))
            .addGroup(pnlHomeLayout.createSequentialGroup()
                .addGap(258, 258, 258)
                .addComponent(lblSelectHome)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlHomeLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(pnlHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblHelp, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlHomeLayout.createSequentialGroup()
                        .addGroup(pnlHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(scrScrollListHome, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnlHomeLayout.createSequentialGroup()
                                .addComponent(lblTasksDueHome)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblCurrentDateHome)))
                        .addGap(231, 231, 231))))
        );
        pnlHomeLayout.setVerticalGroup(
            pnlHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHomeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitleHome, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(lblSelectHome)
                .addGap(39, 39, 39)
                .addGroup(pnlHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btgNotesHome, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btgTasksHome, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btgPlantsHome, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTasksDueHome)
                    .addComponent(lblCurrentDateHome))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrScrollListHome, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addComponent(lblHelp)
                .addContainerGap())
        );

        tabScreen.addTab("Home", pnlHome);

        btnSavePlant.setText("Save");
        btnSavePlant.setEnabled(false);
        btnSavePlant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSavePlantActionPerformed(evt);
            }
        });

        txaNotesPlant.setColumns(20);
        txaNotesPlant.setEditable(false);
        txaNotesPlant.setRows(5);
        txaNotesPlant.setText("\n");
        scrNotesPlant.setViewportView(txaNotesPlant);

        btnAddPlant.setText("Add");
        btnAddPlant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddPlantActionPerformed(evt);
            }
        });

        lblSortPlant.setText("Sort By:");

        cmbSortPlant.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ascending", "descending", "alphabetically by labels" }));
        cmbSortPlant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbSortPlantActionPerformed(evt);
            }
        });

        btnCancelPlant.setText("Cancel");
        btnCancelPlant.setEnabled(false);
        btnCancelPlant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelPlantActionPerformed(evt);
            }
        });

        lblLabelPlant.setText("Assigned Label:");
        lblLabelPlant.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        btnAddLabelPlant.setText("Add Label");
        btnAddLabelPlant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddLabelPlantActionPerformed(evt);
            }
        });

        btnDeletePlant.setText("Delete Plant");
        btnDeletePlant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeletePlantActionPerformed(evt);
            }
        });

        btnEditPlant.setText("Edit");
        btnEditPlant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditPlantActionPerformed(evt);
            }
        });

        txtNamePlant.setEditable(false);
        txtNamePlant.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtNamePlant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNamePlantActionPerformed(evt);
            }
        });

        lblHeadingPlant.setText("Plant Manager");
        lblHeadingPlant.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N

        lstListPlant.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Plant 1", "Plant 2", "Plant 3", "Plant 4", "Plant 5", "Plant 6", "Plant 7", "Plant 8", "Plant 9", "Plant 10", "Plant 11", "Plant 12", "Plant 13", "Plant 14", "Plant 15", "Plant 16", "Plant 17", "Plant 18", "Plant 19", "Plant 20" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        lstListPlant.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lstListPlant.setSelectedIndex(0);
        lstListPlant.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lstListPlantMouseClicked(evt);
            }
        });
        lstListPlant.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstListPlantValueChanged(evt);
            }
        });
        scrListPlant.setViewportView(lstListPlant);

        txtAssignedLabelPlant.setEditable(false);
        txtAssignedLabelPlant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAssignedLabelPlantActionPerformed(evt);
            }
        });

        cmbLabelPlant.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "high priority", "medium priority", "low priority", "in pdf", "completed" }));
        cmbLabelPlant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbLabelPlantActionPerformed(evt);
            }
        });

        txtAddLabelPlant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAddLabelPlantActionPerformed(evt);
            }
        });

        btnAddLabelTXTPlant.setText("Add Label");
        btnAddLabelTXTPlant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddLabelTXTPlantActionPerformed(evt);
            }
        });

        lblChangeLabelPlant.setText("Change Label:");
        lblChangeLabelPlant.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        lblDefaultLabelPlant.setText("Default Labels");

        lblAddOwnLabelPlant.setText("Add your own Label");

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator2.setForeground(new java.awt.Color(102, 102, 102));

        javax.swing.GroupLayout pnlPlantManagerLayout = new javax.swing.GroupLayout(pnlPlantManager);
        pnlPlantManager.setLayout(pnlPlantManagerLayout);
        pnlPlantManagerLayout.setHorizontalGroup(
            pnlPlantManagerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPlantManagerLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(pnlPlantManagerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlPlantManagerLayout.createSequentialGroup()
                        .addComponent(txtAddPlant, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAddPlant))
                    .addGroup(pnlPlantManagerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(pnlPlantManagerLayout.createSequentialGroup()
                            .addComponent(lblSortPlant)
                            .addGap(18, 18, 18)
                            .addComponent(cmbSortPlant, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addComponent(scrListPlant, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlPlantManagerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPlantManagerLayout.createSequentialGroup()
                        .addComponent(btnSavePlant)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCancelPlant))
                    .addComponent(lblLabelPlant)
                    .addComponent(scrNotesPlant)
                    .addComponent(txtAssignedLabelPlant)
                    .addGroup(pnlPlantManagerLayout.createSequentialGroup()
                        .addComponent(btnAddLabelPlant)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAddLabelTXTPlant))
                    .addGroup(pnlPlantManagerLayout.createSequentialGroup()
                        .addGroup(pnlPlantManagerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblChangeLabelPlant)
                            .addGroup(pnlPlantManagerLayout.createSequentialGroup()
                                .addGroup(pnlPlantManagerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cmbLabelPlant, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblDefaultLabelPlant))
                                .addGap(4, 4, 4)
                                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(5, 5, 5)
                        .addGroup(pnlPlantManagerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtAddLabelPlant, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblAddOwnLabelPlant)))
                    .addGroup(pnlPlantManagerLayout.createSequentialGroup()
                        .addGroup(pnlPlantManagerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblHeadingPlant)
                            .addComponent(txtNamePlant, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnEditPlant)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDeletePlant)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlPlantManagerLayout.setVerticalGroup(
            pnlPlantManagerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPlantManagerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblHeadingPlant)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlPlantManagerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblSortPlant, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlPlantManagerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnEditPlant)
                        .addComponent(btnDeletePlant)
                        .addComponent(cmbSortPlant, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtNamePlant, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlPlantManagerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlPlantManagerLayout.createSequentialGroup()
                        .addComponent(scrListPlant, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlPlantManagerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtAddPlant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAddPlant)))
                    .addGroup(pnlPlantManagerLayout.createSequentialGroup()
                        .addComponent(scrNotesPlant, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlPlantManagerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnSavePlant)
                            .addComponent(btnCancelPlant))
                        .addGap(1, 1, 1)
                        .addComponent(lblLabelPlant)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtAssignedLabelPlant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(pnlPlantManagerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlPlantManagerLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblChangeLabelPlant)
                                .addGap(8, 8, 8)
                                .addGroup(pnlPlantManagerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblDefaultLabelPlant)
                                    .addComponent(lblAddOwnLabelPlant))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pnlPlantManagerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(cmbLabelPlant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtAddLabelPlant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pnlPlantManagerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnAddLabelPlant)
                                    .addComponent(btnAddLabelTXTPlant)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPlantManagerLayout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(58, Short.MAX_VALUE))
        );

        tabScreen.addTab("Plant Manager", pnlPlantManager);

        lstListNote.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Note 1", "Note 2", "Note 3", "Note 4", "Note 5", "Note 6", "Note 7", "Note 8", "Note 9", "Note 10", "Note 11", "Note 12", "Note 13", "Note 14", "Note 15", "Note 16", "Note 17", "Note 18", "Note 19", "Note 20" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        lstListNote.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lstListNote.setSelectedIndex(0);
        lstListNote.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lstListNoteMousePressed(evt);
            }
        });
        lstListNote.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstListNoteValueChanged(evt);
            }
        });
        scrListNote.setViewportView(lstListNote);

        lblHeadingNote.setText("Encrypted Notes Manager");
        lblHeadingNote.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N

        btnSaveNote.setText("Save");
        btnSaveNote.setEnabled(false);
        btnSaveNote.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveNoteActionPerformed(evt);
            }
        });

        btnEditNote.setText("Edit");
        btnEditNote.setEnabled(false);
        btnEditNote.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditNoteActionPerformed(evt);
            }
        });

        btnDeleteNote.setText("Delete");
        btnDeleteNote.setEnabled(false);
        btnDeleteNote.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteNoteActionPerformed(evt);
            }
        });

        txaNote.setColumns(20);
        txaNote.setEditable(false);
        txaNote.setRows(5);
        txaNote.setText("Please Press the \"Unlock Button\" to enter your password and view the contents\n");
        scrNote.setViewportView(txaNote);

        lblSortNote.setText("Sort By:");

        cmbSortNote.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ascending", "descending" }));
        cmbSortNote.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbSortNoteActionPerformed(evt);
            }
        });

        btnCancelNote.setText("Cancel");
        btnCancelNote.setEnabled(false);
        btnCancelNote.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelNoteActionPerformed(evt);
            }
        });

        btnAddNote.setText("Add");
        btnAddNote.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddNoteActionPerformed(evt);
            }
        });

        txtNameNote.setEditable(false);
        txtNameNote.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtNameNote.setText("Note 1");
        txtNameNote.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameNoteActionPerformed(evt);
            }
        });

        btnChangePasswordNote.setText("Change Password");
        btnChangePasswordNote.setEnabled(false);
        btnChangePasswordNote.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChangePasswordNoteActionPerformed(evt);
            }
        });

        txtPasswordNote.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPasswordNoteActionPerformed(evt);
            }
        });

        lblPassword.setText("Enter Password:");

        btnLockNote.setText("Lock");
        btnLockNote.setEnabled(false);
        btnLockNote.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLockNoteActionPerformed(evt);
            }
        });

        btnUnlockNote.setText("Unlock");
        btnUnlockNote.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUnlockNoteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlEncryptedNotesManagerLayout = new javax.swing.GroupLayout(pnlEncryptedNotesManager);
        pnlEncryptedNotesManager.setLayout(pnlEncryptedNotesManagerLayout);
        pnlEncryptedNotesManagerLayout.setHorizontalGroup(
            pnlEncryptedNotesManagerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEncryptedNotesManagerLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(pnlEncryptedNotesManagerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlEncryptedNotesManagerLayout.createSequentialGroup()
                        .addComponent(lblSortNote)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbSortNote, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pnlEncryptedNotesManagerLayout.createSequentialGroup()
                        .addComponent(txtAddNote)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAddNote))
                    .addComponent(scrListNote, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 39, Short.MAX_VALUE)
                .addGroup(pnlEncryptedNotesManagerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlEncryptedNotesManagerLayout.createSequentialGroup()
                        .addComponent(txtNameNote, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(111, 111, 111)
                        .addComponent(btnEditNote)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDeleteNote))
                    .addGroup(pnlEncryptedNotesManagerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(scrNote, javax.swing.GroupLayout.PREFERRED_SIZE, 461, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(pnlEncryptedNotesManagerLayout.createSequentialGroup()
                            .addGroup(pnlEncryptedNotesManagerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(pnlEncryptedNotesManagerLayout.createSequentialGroup()
                                    .addComponent(lblPassword)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtPasswordNote, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(btnChangePasswordNote))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(pnlEncryptedNotesManagerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(btnLockNote, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnUnlockNote, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnSaveNote)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnCancelNote))))
                .addGap(35, 35, 35))
            .addGroup(pnlEncryptedNotesManagerLayout.createSequentialGroup()
                .addGap(239, 239, 239)
                .addComponent(lblHeadingNote)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlEncryptedNotesManagerLayout.setVerticalGroup(
            pnlEncryptedNotesManagerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEncryptedNotesManagerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblHeadingNote)
                .addGap(12, 12, 12)
                .addGroup(pnlEncryptedNotesManagerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbSortNote, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSortNote, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEditNote)
                    .addComponent(btnDeleteNote)
                    .addComponent(txtNameNote, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlEncryptedNotesManagerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(scrListNote, javax.swing.GroupLayout.DEFAULT_SIZE, 368, Short.MAX_VALUE)
                    .addComponent(scrNote))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlEncryptedNotesManagerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelNote)
                    .addComponent(btnSaveNote)
                    .addComponent(txtAddNote, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAddNote)
                    .addComponent(txtPasswordNote, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPassword)
                    .addComponent(btnUnlockNote))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlEncryptedNotesManagerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnChangePasswordNote)
                    .addComponent(btnLockNote))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        tabScreen.addTab("Encrypted Notes Manager", pnlEncryptedNotesManager);

        btnDeleteTask.setText("Delete");
        btnDeleteTask.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteTaskActionPerformed(evt);
            }
        });

        btnSaveTask.setText("Save");
        btnSaveTask.setEnabled(false);
        btnSaveTask.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveTaskActionPerformed(evt);
            }
        });

        btnEditTask.setText("Edit");
        btnEditTask.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditTaskActionPerformed(evt);
            }
        });

        btnCancelTask.setText("Cancel");
        btnCancelTask.setEnabled(false);
        btnCancelTask.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelTaskActionPerformed(evt);
            }
        });

        txaNotesTask.setColumns(20);
        txaNotesTask.setEditable(false);
        txaNotesTask.setRows(5);
        scrNoteTask.setViewportView(txaNotesTask);

        tglCompleteTask.setText("Task Completed");
        tglCompleteTask.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tglCompleteTaskActionPerformed(evt);
            }
        });

        lblHeadingTask.setText("Task Manager");
        lblHeadingTask.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N

        lstListTask.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Task 1", "Task 2", "Task 3", "Task 4", "Task 5", "Task 6", "Task 7", "Task 8", "Task 9", "Task 10", "Task 11", "Task 12", "Task 13", "Task 14", "Task 15", "Task 16", "Task 17", "Task 18", "Task 19", "Task 20" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        lstListTask.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lstListTask.setSelectedIndex(0);
        lstListTask.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lstListTaskMouseClicked(evt);
            }
        });
        lstListTask.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstListTaskValueChanged(evt);
            }
        });
        scrListTask.setViewportView(lstListTask);

        cmbFilterTask.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "none", "high priority", "medium priority", "low priority", "in pdf", "completed" }));
        cmbFilterTask.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbFilterTaskActionPerformed(evt);
            }
        });

        lblFilterTask.setText("Filter By:");

        lblSortTask.setText("Sort By:");

        cmbSortTask.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ascending", "descending", "alphabetically by labels", "by due date" }));
        cmbSortTask.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbSortTaskActionPerformed(evt);
            }
        });

        lblAssignedLabelTask.setText("Assigned Labels");
        lblAssignedLabelTask.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        btnAddTask.setText("Add");
        btnAddTask.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddTaskActionPerformed(evt);
            }
        });

        lblDueDateTask.setText("Due Date:");
        lblDueDateTask.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        btnSaveDateTask.setText("Save");
        btnSaveDateTask.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveDateTaskActionPerformed(evt);
            }
        });

        txtNameTask.setEditable(false);
        txtNameTask.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtNameTask.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameTaskActionPerformed(evt);
            }
        });

        lblChangeLabelTask.setText("Change Label:");
        lblChangeLabelTask.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        lblDefaultLabelTask.setText("Default Labels");

        cmbLabelTask.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "high priority", "medium priority", "low priority", "in pdf", "completed" }));
        cmbLabelTask.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbLabelTaskActionPerformed(evt);
            }
        });

        btnAddLabelTask.setText("Add Label");
        btnAddLabelTask.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddLabelTaskActionPerformed(evt);
            }
        });

        txtAddLabelTask.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAddLabelTaskActionPerformed(evt);
            }
        });

        btnAddLabelTXTTask.setText("Add Label");
        btnAddLabelTXTTask.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddLabelTXTTaskActionPerformed(evt);
            }
        });

        lblAddLabelTask.setText("Add your own Label");

        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator3.setForeground(new java.awt.Color(102, 102, 102));

        txtAssignedLabelTask.setEditable(false);
        txtAssignedLabelTask.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAssignedLabelTaskActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlTaskManagerLayout = new javax.swing.GroupLayout(pnlTaskManager);
        pnlTaskManager.setLayout(pnlTaskManagerLayout);
        pnlTaskManagerLayout.setHorizontalGroup(
            pnlTaskManagerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTaskManagerLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(pnlTaskManagerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlTaskManagerLayout.createSequentialGroup()
                        .addComponent(lblSortTask)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cmbSortTask, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(scrListTask, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlTaskManagerLayout.createSequentialGroup()
                        .addComponent(lblFilterTask)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbFilterTask, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlTaskManagerLayout.createSequentialGroup()
                        .addComponent(txtAddTask, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAddTask)))
                .addGap(18, 18, 18)
                .addGroup(pnlTaskManagerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlTaskManagerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(pnlTaskManagerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(pnlTaskManagerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(pnlTaskManagerLayout.createSequentialGroup()
                                    .addComponent(lblDueDateTask)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(dpDueDateTask, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTaskManagerLayout.createSequentialGroup()
                                    .addComponent(tglCompleteTask)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnEditTask)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btnDeleteTask))
                                .addComponent(scrNoteTask, javax.swing.GroupLayout.DEFAULT_SIZE, 461, Short.MAX_VALUE)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTaskManagerLayout.createSequentialGroup()
                                    .addComponent(btnSaveTask)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btnCancelTask)))
                            .addComponent(txtNameTask, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSaveDateTask))
                        .addGroup(pnlTaskManagerLayout.createSequentialGroup()
                            .addComponent(btnAddLabelTask)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnAddLabelTXTTask))
                        .addGroup(pnlTaskManagerLayout.createSequentialGroup()
                            .addGroup(pnlTaskManagerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(cmbLabelTask, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblDefaultLabelTask))
                            .addGap(4, 4, 4)
                            .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(5, 5, 5)
                            .addGroup(pnlTaskManagerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtAddLabelTask, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblAddLabelTask)))
                        .addComponent(lblAssignedLabelTask)
                        .addComponent(txtAssignedLabelTask))
                    .addComponent(lblChangeLabelTask)
                    .addGroup(pnlTaskManagerLayout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(lblHeadingTask, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 57, Short.MAX_VALUE))
        );
        pnlTaskManagerLayout.setVerticalGroup(
            pnlTaskManagerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTaskManagerLayout.createSequentialGroup()
                .addGroup(pnlTaskManagerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlTaskManagerLayout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(pnlTaskManagerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmbSortTask, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblSortTask)))
                    .addGroup(pnlTaskManagerLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblHeadingTask)
                        .addGap(10, 10, 10)
                        .addComponent(txtNameTask, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlTaskManagerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTaskManagerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(tglCompleteTask)
                        .addGroup(pnlTaskManagerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmbFilterTask, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnDeleteTask)
                            .addComponent(btnEditTask)))
                    .addComponent(lblFilterTask, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGroup(pnlTaskManagerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(pnlTaskManagerLayout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(scrListTask, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlTaskManagerLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(scrNoteTask, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlTaskManagerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnCancelTask)
                            .addComponent(btnSaveTask))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblAssignedLabelTask)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtAssignedLabelTask, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblChangeLabelTask)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlTaskManagerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(pnlTaskManagerLayout.createSequentialGroup()
                                .addGroup(pnlTaskManagerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblDefaultLabelTask)
                                    .addComponent(lblAddLabelTask))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pnlTaskManagerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(cmbLabelTask, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtAddLabelTask, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pnlTaskManagerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnAddLabelTask)
                                    .addComponent(btnAddLabelTXTTask)))
                            .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(pnlTaskManagerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblDueDateTask)
                            .addComponent(dpDueDateTask, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlTaskManagerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAddTask, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAddTask)
                    .addComponent(btnSaveDateTask))
                .addContainerGap(63, Short.MAX_VALUE))
        );

        tabScreen.addTab("Task Manager", pnlTaskManager);

        mnuQuickActions.setText("Quick Actions");

        mniDownloadPlantList.setText("Download Plant List");
        mniDownloadPlantList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniDownloadPlantListActionPerformed(evt);
            }
        });
        mnuQuickActions.add(mniDownloadPlantList);

        mniDownloadTaskList.setText("Download Task List");
        mniDownloadTaskList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniDownloadTaskListActionPerformed(evt);
            }
        });
        mnuQuickActions.add(mniDownloadTaskList);

        mniSyncTasks.setText("Sync Tasks");
        mniSyncTasks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniSyncTasksActionPerformed(evt);
            }
        });
        mnuQuickActions.add(mniSyncTasks);

        mniSaveData.setText("Save Data");
        mniSaveData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniSaveDataActionPerformed(evt);
            }
        });
        mnuQuickActions.add(mniSaveData);

        mnuMenu.add(mnuQuickActions);

        mnuHelp.setText("Help");

        mniContactUs.setText("Contact Us");
        mniContactUs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniContactUsActionPerformed(evt);
            }
        });
        mnuHelp.add(mniContactUs);

        mniFAQ.setText("FAQ");
        mniFAQ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniFAQActionPerformed(evt);
            }
        });
        mnuHelp.add(mniFAQ);

        mnuMenu.add(mnuHelp);

        setJMenuBar(mnuMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(tabScreen)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabScreen)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btgPlantsHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btgPlantsHomeActionPerformed
        tabScreen.setSelectedIndex(1);
    }//GEN-LAST:event_btgPlantsHomeActionPerformed

    private void lblHelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lblHelpActionPerformed
       new HelpUI().setVisible(true);
    }//GEN-LAST:event_lblHelpActionPerformed

    private void btgNotesHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btgNotesHomeActionPerformed
        tabScreen.setSelectedIndex(2);
    }//GEN-LAST:event_btgNotesHomeActionPerformed

    private void btnSavePlantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSavePlantActionPerformed
        String message = manager.edit(PlantCareManager.PLANT, lstListPlant.getSelectedValue(), txaNotesPlant.getText(), txtNamePlant.getText());
        if (message != null) {
            new ErrorMessageUI(message).setVisible(true);
            return;
        }
        txtNamePlant.setEditable(false);
        txaNotesPlant.setEditable(false);
        btnSavePlant.setEnabled(false);
        btnCancelPlant.setEnabled(false);
        lstListPlant.setModel(UIManager.toListModel(manager.getSortList(PlantCareManager.ASCENDING, PlantCareManager.PLANT)));
    }//GEN-LAST:event_btnSavePlantActionPerformed

    private void btnEditPlantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditPlantActionPerformed
       txtNamePlant.setEditable(true);
       txaNotesPlant.setEditable(true);
       btnSavePlant.setEnabled(true);
        btnCancelPlant.setEnabled(true);
    }//GEN-LAST:event_btnEditPlantActionPerformed

    private void btnDeletePlantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeletePlantActionPerformed
        manager.delete(PlantCareManager.PLANT, lstListPlant.getSelectedValue());
        lstListPlant.setModel(UIManager.toListModel(manager.getSortList(PlantCareManager.ASCENDING, PlantCareManager.PLANT)));
        lstListPlant.setSelectedIndex(0);
    }//GEN-LAST:event_btnDeletePlantActionPerformed

    private void btnCancelPlantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelPlantActionPerformed
        setPlantValues(lstListPlant.getSelectedValue());
        txtNamePlant.setEditable(false);
        txaNotesPlant.setEditable(false);
        btnSavePlant.setEnabled(false);
        btnCancelPlant.setEnabled(false);
    }//GEN-LAST:event_btnCancelPlantActionPerformed

    private void btnSaveNoteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveNoteActionPerformed
        String message = manager.edit(PlantCareManager.ENCRYPTED_NOTE, lstListNote.getSelectedValue(), txaNote.getText(), txtNameNote.getText());
        if (message != null) {
            new ErrorMessageUI(message).setVisible(true);
            return;
        }
        txtNameNote.setEditable(false);
        txaNote.setEditable(false);
        btnSaveNote.setEnabled(false);
        btnCancelNote.setEnabled(false);
        
    }//GEN-LAST:event_btnSaveNoteActionPerformed

    private void btnEditNoteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditNoteActionPerformed
        txtNameNote.setEditable(true);
        txaNote.setEditable(true);
        btnSaveNote.setEnabled(true);
        btnCancelNote.setEnabled(true);
    }//GEN-LAST:event_btnEditNoteActionPerformed

    private void btnDeleteNoteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteNoteActionPerformed
        manager.delete(PlantCareManager.ENCRYPTED_NOTE, lstListNote.getSelectedValue());
        lstListNote.setModel(UIManager.toListModel(manager.getSortList(PlantCareManager.ASCENDING, PlantCareManager.ENCRYPTED_NOTE)));
        lstListNote.setSelectedIndex(0);
        btnDeleteNote.setEnabled(false);
    }//GEN-LAST:event_btnDeleteNoteActionPerformed

    private void btnDeleteTaskActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteTaskActionPerformed
        manager.delete(PlantCareManager.TASK, lstListTask.getSelectedValue());
        lstListTask.setModel(UIManager.toListModel(manager.getSortList(PlantCareManager.ASCENDING, PlantCareManager.TASK)));
        lstListTask.setSelectedIndex(0);
    }//GEN-LAST:event_btnDeleteTaskActionPerformed

    private void btnSaveTaskActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveTaskActionPerformed
        String message = manager.edit(PlantCareManager.TASK, lstListNote.getSelectedValue(), txaNotesTask.getText(), txtNameTask.getText());
        if (message != null) {
            new ErrorMessageUI(message).setVisible(true);
            return;
        }
        txtNameTask.setEditable(false);
        txaNotesTask.setEditable(false);
        
        btnSaveTask.setEnabled(false);
        btnCancelTask.setEnabled(false);
    }//GEN-LAST:event_btnSaveTaskActionPerformed

    private void btnEditTaskActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditTaskActionPerformed
        txtNameTask.setEditable(true);
        txaNotesTask.setEditable(true);
        btnSaveTask.setEnabled(true);
        btnCancelTask.setEnabled(true);
    }//GEN-LAST:event_btnEditTaskActionPerformed

    private void btnCancelTaskActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelTaskActionPerformed
        setTaskValues(lstListTask.getSelectedValue());
        txtNameTask.setEditable(false);
        txaNotesTask.setEditable(false);
        btnSaveTask.setEnabled(false);
        btnCancelTask.setEnabled(false);
    }//GEN-LAST:event_btnCancelTaskActionPerformed

    private void tglCompleteTaskActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tglCompleteTaskActionPerformed
        manager.setTaskCompleted(lstListTask.getSelectedValue());
        setToggleButtonValues();
    }//GEN-LAST:event_tglCompleteTaskActionPerformed

    private void btnSaveDateTaskActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveDateTaskActionPerformed
        if(dpDueDateTask.isValid() == false) {
            new ErrorMessageUI("Please Enter a Valid Date").setVisible(true);
        }
        manager.changeTaskDate(lstListTask.getSelectedValue(), dpDueDateTask.getDate());
        setTaskValues(lstListTask.getSelectedValue());
    }//GEN-LAST:event_btnSaveDateTaskActionPerformed

    private void txtNameNoteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameNoteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameNoteActionPerformed

    private void txtPasswordNoteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPasswordNoteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPasswordNoteActionPerformed

    private void btgTasksHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btgTasksHomeActionPerformed
        tabScreen.setSelectedIndex(3);
    }//GEN-LAST:event_btgTasksHomeActionPerformed

    private void btnAddLabelPlantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddLabelPlantActionPerformed
        String message = manager.changeAssignedLabel(PlantCareManager.PLANT, lstListPlant.getSelectedValue(), cmbLabelPlant.getItemAt(cmbLabelPlant.getSelectedIndex()));
        if (message != null) {
            new ErrorMessageUI(message).setVisible(true);
            return;
        }
        setPlantValues(lstListPlant.getSelectedValue());
    }//GEN-LAST:event_btnAddLabelPlantActionPerformed

    private void txtAssignedLabelPlantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAssignedLabelPlantActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAssignedLabelPlantActionPerformed

    private void txtAddLabelPlantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAddLabelPlantActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAddLabelPlantActionPerformed

    private void btnAddLabelTXTPlantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddLabelTXTPlantActionPerformed
        manager.changeAssignedLabel(PlantCareManager.PLANT, lstListPlant.getSelectedValue(), txtAddLabelPlant.getText());
        setPlantValues(lstListPlant.getSelectedValue());
    }//GEN-LAST:event_btnAddLabelTXTPlantActionPerformed

    private void btnAddLabelTaskActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddLabelTaskActionPerformed
        manager.changeAssignedLabel(PlantCareManager.TASK, lstListTask.getSelectedValue(), cmbLabelTask.getItemAt(cmbLabelTask.getSelectedIndex()));
        setTaskValues(lstListTask.getSelectedValue());
    }//GEN-LAST:event_btnAddLabelTaskActionPerformed

    private void txtAddLabelTaskActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAddLabelTaskActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAddLabelTaskActionPerformed

    private void btnAddLabelTXTTaskActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddLabelTXTTaskActionPerformed
        String message = manager.changeAssignedLabel(PlantCareManager.TASK, lstListTask.getSelectedValue(), txtAddLabelTask.getText());
        if (message != null) {
            new ErrorMessageUI(message).setVisible(true);
            return;
        }
        setTaskValues(lstListTask.getSelectedValue());
    }//GEN-LAST:event_btnAddLabelTXTTaskActionPerformed

    private void txtAssignedLabelTaskActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAssignedLabelTaskActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAssignedLabelTaskActionPerformed

    private void cmbSortPlantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbSortPlantActionPerformed
        lstListPlant.setModel(UIManager.toListModel(manager.getSortList((String) cmbSortPlant.getSelectedItem(), PlantCareManager.PLANT)));
    }//GEN-LAST:event_cmbSortPlantActionPerformed

    private void cmbSortTaskActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbSortTaskActionPerformed
        lstListTask.setModel(UIManager.toListModel(manager.getSortList((String) cmbSortTask.getSelectedItem(), PlantCareManager.TASK)));
    }//GEN-LAST:event_cmbSortTaskActionPerformed

    private void txtNamePlantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNamePlantActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNamePlantActionPerformed

    private void cmbLabelPlantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbLabelPlantActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbLabelPlantActionPerformed

    private void txtNameTaskActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameTaskActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameTaskActionPerformed

    private void btnCancelNoteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelNoteActionPerformed
        setNoteValues(lstListNote.getSelectedValue());
        txtNameNote.setEditable(false);
        txaNote.setEditable(false);
        btnSaveNote.setEnabled(false);
        btnCancelNote.setEnabled(false);
    }//GEN-LAST:event_btnCancelNoteActionPerformed

    private void mniDownloadTaskListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniDownloadTaskListActionPerformed
        PDFManagerUI pdf = new PDFManagerUI(manager);
        pdf.setVisible(true);
        pdf.setScreen(1);
    }//GEN-LAST:event_mniDownloadTaskListActionPerformed

    private void btnAddPlantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddPlantActionPerformed
        String message = manager.add(PlantCareManager.PLANT, txtAddPlant.getText());
        if (message != null) {
            new ErrorMessageUI(message).setVisible(true);
        }
        lstListPlant.setModel(UIManager.toListModel(manager.getSortList(PlantCareManager.ASCENDING, PlantCareManager.PLANT)));
        txtAddPlant.setText("");
    }//GEN-LAST:event_btnAddPlantActionPerformed

    private void lstListPlantMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lstListPlantMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lstListPlantMouseClicked

    private void lstListNoteMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lstListNoteMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_lstListNoteMousePressed

    private void lstListTaskMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lstListTaskMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lstListTaskMouseClicked

    private void lstListTaskValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstListTaskValueChanged
        setTaskValues(lstListTask.getSelectedValue());
    }//GEN-LAST:event_lstListTaskValueChanged

    private void lstListNoteValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstListNoteValueChanged
        setNoteValues(lstListNote.getSelectedValue());
    }//GEN-LAST:event_lstListNoteValueChanged

    private void lstListPlantValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstListPlantValueChanged
        setPlantValues(lstListPlant.getSelectedValue());
    }//GEN-LAST:event_lstListPlantValueChanged

    private void btnLockNoteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLockNoteActionPerformed
        manager.lockNote(lstListNote.getSelectedValue());
        setNoteValues(lstListNote.getSelectedValue());
        btnEditNote.setEnabled(false);
        btnDeleteNote.setEnabled(false);
        btnChangePasswordNote.setEnabled(false);
        btnLockNote.setEnabled(false);
    }//GEN-LAST:event_btnLockNoteActionPerformed

    private void btnChangePasswordNoteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChangePasswordNoteActionPerformed
        String message = manager.changePassword(lstListNote.getSelectedValue(), txtPasswordNote.getText());
        txtPasswordNote.setText("");
        if (message != null) {
            new ErrorMessageUI(message).setVisible(true);
        }
    }//GEN-LAST:event_btnChangePasswordNoteActionPerformed

    private void btnAddTaskActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddTaskActionPerformed
        String message = manager.add(PlantCareManager.TASK, txtAddTask.getText());
        if (message != null) {
            new ErrorMessageUI(message).setVisible(true);
        }
        lstListTask.setModel(UIManager.toListModel(manager.getSortList(PlantCareManager.ASCENDING, PlantCareManager.TASK)));
        txtAddTask.setText("");
    }//GEN-LAST:event_btnAddTaskActionPerformed

    private void btnAddNoteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddNoteActionPerformed
        String message = manager.add(PlantCareManager.ENCRYPTED_NOTE, txtAddNote.getText());
        if (message != null) {
            new ErrorMessageUI(message).setVisible(true);
        }
        lstListNote.setModel(UIManager.toListModel(manager.getSortList(PlantCareManager.ASCENDING, PlantCareManager.ENCRYPTED_NOTE)));
        txtAddNote.setText("");
    }//GEN-LAST:event_btnAddNoteActionPerformed

    private void mniSaveDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniSaveDataActionPerformed
        manager.save();
    }//GEN-LAST:event_mniSaveDataActionPerformed

    private void mniSyncTasksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniSyncTasksActionPerformed
        PDFManagerUI pdf = new PDFManagerUI(manager);
        pdf.setVisible(true);
        pdf.setScreen(2);
    }//GEN-LAST:event_mniSyncTasksActionPerformed

    private void mniDownloadPlantListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniDownloadPlantListActionPerformed
        PDFManagerUI pdf = new PDFManagerUI(manager);
        pdf.setVisible(true);
        pdf.setScreen(0);
    }//GEN-LAST:event_mniDownloadPlantListActionPerformed

    private void mniContactUsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniContactUsActionPerformed
        new HelpContactUI().setVisible(true);
    }//GEN-LAST:event_mniContactUsActionPerformed

    private void cmbSortNoteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbSortNoteActionPerformed
         lstListNote.setModel(UIManager.toListModel(manager.getSortList((String) cmbSortNote.getSelectedItem(), PlantCareManager.ENCRYPTED_NOTE)));
    }//GEN-LAST:event_cmbSortNoteActionPerformed

    private void btnUnlockNoteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUnlockNoteActionPerformed
        String message = manager.unlockNote(lstListNote.getSelectedValue(), txtPasswordNote.getText());
        if(message != null) {
            new ErrorMessageUI(message).setVisible(true);
            txtPasswordNote.setText("");
            return;
        }
        setNoteValues(lstListNote.getSelectedValue());
        txtPasswordNote.setText("");
        btnEditNote.setEnabled(true);
        btnDeleteNote.setEnabled(true);
        btnChangePasswordNote.setEnabled(true);
        btnLockNote.setEnabled(true);
    }//GEN-LAST:event_btnUnlockNoteActionPerformed

    private void mniFAQActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniFAQActionPerformed
        new HelpUI().setVisible(true);
    }//GEN-LAST:event_mniFAQActionPerformed

    private void cmbFilterTaskActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbFilterTaskActionPerformed
        if(cmbFilterTask.getSelectedItem().equals("none")) {
            lstListTask.setModel(UIManager.toListModel(manager.getSortList((String) cmbSortTask.getSelectedItem(), PlantCareManager.TASK)));
            return;
        }
        lstListTask.setModel(UIManager.toListModel(manager.getFilterList((String) cmbFilterTask.getSelectedItem())));
    }//GEN-LAST:event_cmbFilterTaskActionPerformed

    private void cmbLabelTaskActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbLabelTaskActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbLabelTaskActionPerformed
    
    private void setPlantValues(String name) {
        Plant plant = manager.displayPlant(name);

        if(plant != null) {
            txtNamePlant.setText(plant.getName());
            txaNotesPlant.setText(plant.getNote());
            txtAssignedLabelPlant.setText(plant.getLabel());
        }
    }
    
    private void setTaskValues(String name) {
        Task task = manager.displayTask(name);

        if(task != null) {
            txtNameTask.setText(task.getName());
            txaNotesTask.setText(task.getNote());
            txtAssignedLabelTask.setText(task.getLabel());
            dpDueDateTask.setDate(task.getDueDate());
            tglCompleteTask.setSelected(task.getDoneOrNot());
            setToggleButtonValues();
        }
    }
    
    private void setNoteValues(String name) {
        String heading = manager.getNoteHeading(name);
        String content = manager.getNoteContent(name);

        if(heading != null) {
            txtNameNote.setText(heading);
            txaNote.setText(content);
        }
    }
    
    private void setToggleButtonValues() {
        if(tglCompleteTask.isSelected()) {
            tglCompleteTask.setText("Task Complete");
        } if(!tglCompleteTask.isSelected()) {
            tglCompleteTask.setText("Task Incomplete");
        }
    }
    
    private void initLists() {
        lstTasksDue.setModel(UIManager.toListModel(manager.getTasksDueSoon()));
        lstListPlant.setModel(UIManager.toListModel(manager.getSortList(PlantCareManager.ASCENDING, PlantCareManager.PLANT)));
        lstListTask.setModel(UIManager.toListModel(manager.getSortList(PlantCareManager.ASCENDING, PlantCareManager.TASK)));
        lstListNote.setModel(UIManager.toListModel(manager.getSortList(PlantCareManager.ASCENDING, PlantCareManager.ENCRYPTED_NOTE)));
        
        lstListPlant.setSelectedIndex(0);
        lstListTask.setSelectedIndex(0);
        lstListNote.setSelectedIndex(0);
        
        setTaskValues(lstListTask.getSelectedValue());
        setNoteValues(lstListNote.getSelectedValue());
        setPlantValues(lstListNote.getSelectedValue());
        
        
//        cmbLabelPlant.setModel(aModel);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btgNotesHome;
    private javax.swing.JButton btgPlantsHome;
    private javax.swing.JButton btgTasksHome;
    private javax.swing.JButton btnAddLabelPlant;
    private javax.swing.JButton btnAddLabelTXTPlant;
    private javax.swing.JButton btnAddLabelTXTTask;
    private javax.swing.JButton btnAddLabelTask;
    private javax.swing.JButton btnAddNote;
    private javax.swing.JButton btnAddPlant;
    private javax.swing.JButton btnAddTask;
    private javax.swing.JButton btnCancelNote;
    private javax.swing.JButton btnCancelPlant;
    private javax.swing.JButton btnCancelTask;
    private javax.swing.JButton btnChangePasswordNote;
    private javax.swing.JButton btnDeleteNote;
    private javax.swing.JButton btnDeletePlant;
    private javax.swing.JButton btnDeleteTask;
    private javax.swing.JButton btnEditNote;
    private javax.swing.JButton btnEditPlant;
    private javax.swing.JButton btnEditTask;
    private javax.swing.JButton btnLockNote;
    private javax.swing.JButton btnSaveDateTask;
    private javax.swing.JButton btnSaveNote;
    private javax.swing.JButton btnSavePlant;
    private javax.swing.JButton btnSaveTask;
    private javax.swing.JButton btnUnlockNote;
    private javax.swing.JComboBox<String> cmbFilterTask;
    private javax.swing.JComboBox<String> cmbLabelPlant;
    private javax.swing.JComboBox<String> cmbLabelTask;
    private javax.swing.JComboBox<String> cmbSortNote;
    private javax.swing.JComboBox<String> cmbSortPlant;
    private javax.swing.JComboBox<String> cmbSortTask;
    private com.github.lgooddatepicker.components.DatePicker dpDueDateTask;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel lblAddLabelTask;
    private javax.swing.JLabel lblAddOwnLabelPlant;
    private javax.swing.JLabel lblAssignedLabelTask;
    private javax.swing.JLabel lblChangeLabelPlant;
    private javax.swing.JLabel lblChangeLabelTask;
    private javax.swing.JLabel lblCurrentDateHome;
    private javax.swing.JLabel lblDefaultLabelPlant;
    private javax.swing.JLabel lblDefaultLabelTask;
    private javax.swing.JLabel lblDueDateTask;
    private javax.swing.JLabel lblFilterTask;
    private javax.swing.JLabel lblHeadingNote;
    private javax.swing.JLabel lblHeadingPlant;
    private javax.swing.JLabel lblHeadingTask;
    private javax.swing.JButton lblHelp;
    private javax.swing.JLabel lblLabelPlant;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblSelectHome;
    private javax.swing.JLabel lblSortNote;
    private javax.swing.JLabel lblSortPlant;
    private javax.swing.JLabel lblSortTask;
    private javax.swing.JLabel lblTasksDueHome;
    private javax.swing.JLabel lblTitleHome;
    private javax.swing.JList<String> lstListNote;
    private javax.swing.JList<String> lstListPlant;
    private javax.swing.JList<String> lstListTask;
    private javax.swing.JList<String> lstTasksDue;
    private javax.swing.JMenuItem mniContactUs;
    private javax.swing.JMenuItem mniDownloadPlantList;
    private javax.swing.JMenuItem mniDownloadTaskList;
    private javax.swing.JMenuItem mniFAQ;
    private javax.swing.JMenuItem mniSaveData;
    private javax.swing.JMenuItem mniSyncTasks;
    private javax.swing.JMenu mnuHelp;
    private javax.swing.JMenuBar mnuMenu;
    private javax.swing.JMenu mnuQuickActions;
    private javax.swing.JPanel pnlEncryptedNotesManager;
    private javax.swing.JPanel pnlHome;
    private javax.swing.JPanel pnlPlantManager;
    private javax.swing.JPanel pnlTaskManager;
    private javax.swing.JScrollPane scrListNote;
    private javax.swing.JScrollPane scrListPlant;
    private javax.swing.JScrollPane scrListTask;
    private javax.swing.JScrollPane scrNote;
    private javax.swing.JScrollPane scrNoteTask;
    private javax.swing.JScrollPane scrNotesPlant;
    private javax.swing.JScrollPane scrScrollListHome;
    private javax.swing.JTabbedPane tabScreen;
    private javax.swing.JToggleButton tglCompleteTask;
    private javax.swing.JTextArea txaNote;
    private javax.swing.JTextArea txaNotesPlant;
    private javax.swing.JTextArea txaNotesTask;
    private javax.swing.JTextField txtAddLabelPlant;
    private javax.swing.JTextField txtAddLabelTask;
    private javax.swing.JTextField txtAddNote;
    private javax.swing.JTextField txtAddPlant;
    private javax.swing.JTextField txtAddTask;
    private javax.swing.JTextField txtAssignedLabelPlant;
    private javax.swing.JTextField txtAssignedLabelTask;
    private javax.swing.JTextField txtNameNote;
    private javax.swing.JTextField txtNamePlant;
    private javax.swing.JTextField txtNameTask;
    private javax.swing.JTextField txtPasswordNote;
    // End of variables declaration//GEN-END:variables
}
