/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package plantcaremanager.UI;

import javax.swing.DefaultListModel;
import plantcaremanager.UIManager;
import plantcaremanager.PlantCareManager;

/**
 *
 * @author kelvi
 */
public class PDFManagerUI extends javax.swing.JFrame {

    /**
     * Creates new form DownloadTaskList
     */
    
    private PlantCareManager manager = new PlantCareManager();
    
    public PDFManagerUI(PlantCareManager managerObject) {
        manager = managerObject;
        initComponents();
        intitLists();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fchDownload = new javax.swing.JFileChooser();
        lblHeading = new javax.swing.JLabel();
        tabPDF = new javax.swing.JTabbedPane();
        pnlPlants = new javax.swing.JPanel();
        scrUnassignedPlant = new javax.swing.JScrollPane();
        lstUnassignedPlant = new javax.swing.JList<>();
        scrAssignedPlant = new javax.swing.JScrollPane();
        lstAssignedPlant = new javax.swing.JList<>();
        btnAddPlant = new javax.swing.JButton();
        DownloadPlant = new javax.swing.JButton();
        btnRemovePlant = new javax.swing.JButton();
        pnlTask = new javax.swing.JPanel();
        scrUnassignedTask = new javax.swing.JScrollPane();
        lstUnassignedTask = new javax.swing.JList<>();
        scrAssignedTask = new javax.swing.JScrollPane();
        lstAssignedTask = new javax.swing.JList<>();
        btnAddTask = new javax.swing.JButton();
        btnDownloadTask = new javax.swing.JButton();
        btnRemoveTask = new javax.swing.JButton();
        pnlSyncTasks = new javax.swing.JPanel();
        scrUnassignedSync = new javax.swing.JScrollPane();
        lstUnassignedSync = new javax.swing.JList<>();
        btnAddSync = new javax.swing.JButton();
        scrAssignedSync = new javax.swing.JScrollPane();
        lstAssignedSync = new javax.swing.JList<>();
        btnSyncTasks = new javax.swing.JButton();
        btnRemoveSync = new javax.swing.JButton();

        fchDownload.setDialogType(javax.swing.JFileChooser.SAVE_DIALOG);
        fchDownload.setFileSelectionMode(javax.swing.JFileChooser.DIRECTORIES_ONLY);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblHeading.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblHeading.setText("To PDF and Sync Tasks");

        lstUnassignedPlant.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Plant 1", "Plant 2", "Plant 3", "Plant 4", "Plant 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        lstUnassignedPlant.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        scrUnassignedPlant.setViewportView(lstUnassignedPlant);

        lstAssignedPlant.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        scrAssignedPlant.setViewportView(lstAssignedPlant);

        btnAddPlant.setText("Add");
        btnAddPlant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddPlantActionPerformed(evt);
            }
        });

        DownloadPlant.setText("Download");
        DownloadPlant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DownloadPlantActionPerformed(evt);
            }
        });

        btnRemovePlant.setText("Remove");
        btnRemovePlant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemovePlantActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlPlantsLayout = new javax.swing.GroupLayout(pnlPlants);
        pnlPlants.setLayout(pnlPlantsLayout);
        pnlPlantsLayout.setHorizontalGroup(
            pnlPlantsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPlantsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrUnassignedPlant, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addGroup(pnlPlantsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAddPlant)
                    .addComponent(btnRemovePlant))
                .addGap(37, 37, 37)
                .addComponent(scrAssignedPlant, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(pnlPlantsLayout.createSequentialGroup()
                .addGap(155, 155, 155)
                .addComponent(DownloadPlant)
                .addContainerGap(172, Short.MAX_VALUE))
        );
        pnlPlantsLayout.setVerticalGroup(
            pnlPlantsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPlantsLayout.createSequentialGroup()
                .addGroup(pnlPlantsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(pnlPlantsLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(btnAddPlant)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnRemovePlant))
                    .addGroup(pnlPlantsLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(pnlPlantsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(scrAssignedPlant, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(scrUnassignedPlant, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(80, 80, 80)
                .addComponent(DownloadPlant)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        tabPDF.addTab("Plants", pnlPlants);

        lstUnassignedTask.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Task 1", "Task 2", "Task 3", "Task 4", "Task 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        lstUnassignedTask.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        scrUnassignedTask.setViewportView(lstUnassignedTask);

        lstAssignedTask.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        scrAssignedTask.setViewportView(lstAssignedTask);

        btnAddTask.setText("Add");
        btnAddTask.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddTaskActionPerformed(evt);
            }
        });

        btnDownloadTask.setText("Download");
        btnDownloadTask.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDownloadTaskActionPerformed(evt);
            }
        });

        btnRemoveTask.setText("Remove");
        btnRemoveTask.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveTaskActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlTaskLayout = new javax.swing.GroupLayout(pnlTask);
        pnlTask.setLayout(pnlTaskLayout);
        pnlTaskLayout.setHorizontalGroup(
            pnlTaskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTaskLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrUnassignedTask, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlTaskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAddTask, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnRemoveTask, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(38, 38, 38)
                .addComponent(scrAssignedTask, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(pnlTaskLayout.createSequentialGroup()
                .addGap(155, 155, 155)
                .addComponent(btnDownloadTask)
                .addContainerGap(172, Short.MAX_VALUE))
        );
        pnlTaskLayout.setVerticalGroup(
            pnlTaskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTaskLayout.createSequentialGroup()
                .addGroup(pnlTaskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(pnlTaskLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(btnAddTask)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnRemoveTask))
                    .addGroup(pnlTaskLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(pnlTaskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(scrAssignedTask, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(scrUnassignedTask, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(80, 80, 80)
                .addComponent(btnDownloadTask)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        tabPDF.addTab("Tasks", pnlTask);

        lstUnassignedSync.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Task 1", "Task 2", "Task 3", "Task 4", "Task 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        lstUnassignedSync.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        scrUnassignedSync.setViewportView(lstUnassignedSync);

        btnAddSync.setText("Add");
        btnAddSync.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddSyncActionPerformed(evt);
            }
        });

        lstAssignedSync.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        scrAssignedSync.setViewportView(lstAssignedSync);

        btnSyncTasks.setText("Complete and Sync Tasks");
        btnSyncTasks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSyncTasksActionPerformed(evt);
            }
        });

        btnRemoveSync.setText("Remove");
        btnRemoveSync.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveSyncActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlSyncTasksLayout = new javax.swing.GroupLayout(pnlSyncTasks);
        pnlSyncTasks.setLayout(pnlSyncTasksLayout);
        pnlSyncTasksLayout.setHorizontalGroup(
            pnlSyncTasksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlSyncTasksLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrUnassignedSync, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addGroup(pnlSyncTasksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnAddSync)
                    .addComponent(btnRemoveSync))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addComponent(scrAssignedSync, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlSyncTasksLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSyncTasks)
                .addGap(114, 114, 114))
        );
        pnlSyncTasksLayout.setVerticalGroup(
            pnlSyncTasksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSyncTasksLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlSyncTasksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnlSyncTasksLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(btnAddSync)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnRemoveSync)
                        .addGap(20, 20, 20))
                    .addComponent(scrAssignedSync, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                    .addComponent(scrUnassignedSync, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(btnSyncTasks)
                .addGap(37, 37, 37))
        );

        tabPDF.addTab("Sync Tasks", pnlSyncTasks);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(124, 124, 124)
                .addComponent(lblHeading)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(tabPDF)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(lblHeading)
                .addGap(18, 18, 18)
                .addComponent(tabPDF, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnRemoveTaskActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveTaskActionPerformed
        UIManager.switchModels(lstAssignedTask, lstUnassignedTask);
    }//GEN-LAST:event_btnRemoveTaskActionPerformed

    private void btnAddPlantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddPlantActionPerformed
        UIManager.switchModels(lstUnassignedPlant, lstAssignedPlant);
    }//GEN-LAST:event_btnAddPlantActionPerformed

    private void btnRemoveSyncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveSyncActionPerformed
        UIManager.switchModels(lstAssignedSync, lstUnassignedSync);
    }//GEN-LAST:event_btnRemoveSyncActionPerformed

    private void btnRemovePlantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemovePlantActionPerformed
        UIManager.switchModels(lstAssignedPlant, lstUnassignedPlant);
    }//GEN-LAST:event_btnRemovePlantActionPerformed

    private void btnAddTaskActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddTaskActionPerformed
        UIManager.switchModels(lstUnassignedTask, lstAssignedTask);
    }//GEN-LAST:event_btnAddTaskActionPerformed

    private void btnAddSyncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddSyncActionPerformed
        UIManager.switchModels(lstUnassignedSync, lstAssignedSync);
    }//GEN-LAST:event_btnAddSyncActionPerformed

    private void DownloadPlantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DownloadPlantActionPerformed
        manager.toPDF(PlantCareManager.PLANT, UIManager.toArrayList(lstAssignedPlant.getModel()));
    }//GEN-LAST:event_DownloadPlantActionPerformed

    private void btnDownloadTaskActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDownloadTaskActionPerformed
         manager.toPDF(PlantCareManager.TASK, UIManager.toArrayList(lstAssignedPlant.getModel()));
    }//GEN-LAST:event_btnDownloadTaskActionPerformed

    private void btnSyncTasksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSyncTasksActionPerformed
        manager.syncTasks(UIManager.toArrayList(lstAssignedSync.getModel()));
    }//GEN-LAST:event_btnSyncTasksActionPerformed

    
    private void intitLists() {
        lstUnassignedPlant.setModel(UIManager.toListModel(manager.getSortList(PlantCareManager.ASCENDING, PlantCareManager.PLANT)));
        lstUnassignedTask.setModel(UIManager.toListModel(manager.getSortList(PlantCareManager.ASCENDING, PlantCareManager.TASK)));
        lstUnassignedSync.setModel(UIManager.toListModel(manager.getSyncList()));
        lstAssignedPlant.setModel(new DefaultListModel());
        lstAssignedTask.setModel(new DefaultListModel());
        lstAssignedSync.setModel(new DefaultListModel());
        
    }
    
    public void setScreen(int screen) {
        tabPDF.setSelectedIndex(screen);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton DownloadPlant;
    private javax.swing.JButton btnAddPlant;
    private javax.swing.JButton btnAddSync;
    private javax.swing.JButton btnAddTask;
    private javax.swing.JButton btnDownloadTask;
    private javax.swing.JButton btnRemovePlant;
    private javax.swing.JButton btnRemoveSync;
    private javax.swing.JButton btnRemoveTask;
    private javax.swing.JButton btnSyncTasks;
    private javax.swing.JFileChooser fchDownload;
    private javax.swing.JLabel lblHeading;
    private javax.swing.JList<String> lstAssignedPlant;
    private javax.swing.JList<String> lstAssignedSync;
    private javax.swing.JList<String> lstAssignedTask;
    private javax.swing.JList<String> lstUnassignedPlant;
    private javax.swing.JList<String> lstUnassignedSync;
    private javax.swing.JList<String> lstUnassignedTask;
    private javax.swing.JPanel pnlPlants;
    private javax.swing.JPanel pnlSyncTasks;
    private javax.swing.JPanel pnlTask;
    private javax.swing.JScrollPane scrAssignedPlant;
    private javax.swing.JScrollPane scrAssignedSync;
    private javax.swing.JScrollPane scrAssignedTask;
    private javax.swing.JScrollPane scrUnassignedPlant;
    private javax.swing.JScrollPane scrUnassignedSync;
    private javax.swing.JScrollPane scrUnassignedTask;
    private javax.swing.JTabbedPane tabPDF;
    // End of variables declaration//GEN-END:variables
}
